name: economy
version: '${version}'
main: org.pantouflemc.economy.Economy
api-version: '1.20'
libraries:
commands:
  economy:
    description: Economy command
    usage: /<command> <subcommand>
  balance:
    description: Check your balance
    usage: /<command>
    permission: economy.balance
  balancetop:
    description: Show the top balances
    usage: /<command>
    permission: economy.balancetop
  pay:
    description: Pay another player
    usage: /<command> <player> <amount>
    permission: economy.pay
permissions:
  economy.*:
    children:
      economy.balance: true
      economy.balancetop: true
      economy.pay: true
      economy.set: true
      economy.add: true
      economy.remove: true
    default: op
  economy.balance:
    default: true
    description: Allows the player to check his balance
  economy.balancetop:
    default: true
    description: Allows the player to see the top balances
  economy.pay:
    default: true
    description: Allows the player to pay another player
  economy.set:
    default: op
    description: Allows the player to set the balance of another player
  economy.add:
    default: op
    description: Allows the player to add money to another player
  economy.remove:
    default: op
    description: Allows the player to remove money from another player
