package org.pantouflemc.economy.database;

public enum DatabaseError {
    ACCOUNT_NOT_FOUND,
    PLAYER_NOT_FOUND,
    PLAYER_ALREADY_HAS_ACCOUNT,
    PLAYER_DOESNT_HAVE_ACCOUNT,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_DOESNT_EXIST,
    ACCOUNT_HAS_NOT_ENOUGH_BALANCE,
    INVALID_AMOUNT,
    UNKNOWN_ERROR,
    CONNECTION_ERROR
}
